### ISSUE TITLE
Execute conversion error

### ISSUE THREAD

**Issue by wangbinglu08** [JoshData/convert-outlook-msg-file#12] opened 2019-12-18 02:43 UTC
Traceback (most recent call last):
  File "test.py", line 4, in <module>
    eml = outlookmsgfile.load('/tmp/333.msg')
  File "/root/work/python/convert-outlook-msg-file/outlookmsgfile.py", line 33, in load
    return load_message_stream(doc.root, True, doc)
  File "/root/work/python/convert-outlook-msg-file/outlookmsgfile.py", line 38, in load_message_stream
    props = parse_properties(entry['__properties_version1.0'], is_top_level, entry, doc)
  File "/root/work/python/convert-outlook-msg-file/outlookmsgfile.py", line 221, in parse_properties
    value = tag_type.load(value)
  File "/root/work/python/convert-outlook-msg-file/outlookmsgfile.py", line 307, in load
    return value.decode("utf8")
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xb7 in position 0: invalid start byte

Thank you for your time

**Comment by Erwane** [comment] 2022-12-09 13:26
Having this too. Do you found a solution ?

**Comment by MartijnVdS** [comment] 2024-02-24 08:19
Could this be a duplicate of the (now solved) issue #24 ?

**Comment by JoshData** [comment] 2024-02-24 11:57
I'll close this but anyone can feel free to open a new issue if needed.

**Closed as completed by JoshData** 2024-02-24 11:57 UTC
